// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"storage/service"
)

// Injectors from wire.go:

func InitContainer() (*Container, error) {
	chunkService := service.NewChunkService()
	heartbeatService, err := service.NewHeartbeatService()
	if err != nil {
		return nil, err
	}
	container := NewContainer(chunkService, heartbeatService)
	return container, nil
}
